apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
spec:
  type: LoadBalancer
  selector:
    app: nodejs-app
  ports:
  - port: 4000
    targetPort: 4000
  
---

apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  selector:
    app: mongo
  ports:
  - port: 27017
    targetPort: 27017

