apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: default
  labels:
    name: nginx-ingress
spec:
  rules:
  - host: fra.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: server-service
            port:
              name: server-port

